name: Windows Build

on:
  push:
    branches:
      - "*"

env:
  PYTHON_VERSION: "3.10"
  FLAKY_TESTS: dontcare

jobs:
  build-windows-x64:
    runs-on: windows-2019
    strategy:
      matrix:
        buildtype: [debug, release]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: omp-node/libnode
          persist-credentials: false
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install deps
        run: |
          choco install nasm
      - name: Environment Info
        run: |
          npx envinfo
      - name: Build
        run: |
          ./vcbuild.bat ${{ matrix.buildtype }} dll
      - name: Upload libnode.dll artifact
        uses: actions/upload-artifact@v4
        with:
          name: libnode-x64-${{ matrix.buildtype }}.dll
          path: out/${{ matrix.buildtype }}/libnode.dll
      - name: Upload libnode.lib artifact
        uses: actions/upload-artifact@v4
        with:
          name: libnode-x64-${{ matrix.buildtype }}.lib
          path: out/${{ matrix.buildtype }}/libnode.lib
      - name: Create a build archive
        uses: vimtor/action-zip@v1.2
        with:
          files: out/${{ matrix.buildtype }}/libnode.lib out/${{ matrix.buildtype }}/libnode.dll
          dest: libnode-win-x64-${{ matrix.buildtype }}.zip
      - name: Release the new binaries
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: "latest"
          files: libnode-win-x64-${{ matrix.buildtype }}.zip
  build-windows-x86:
    runs-on: windows-2019
    strategy:
      matrix:
        buildtype: [debug, release]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: omp-node/libnode
          persist-credentials: false
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install deps
        run: |
          choco install nasm
      - name: Environment Info
        run: |
          npx envinfo
      - name: Build
        run: |
          ./vcbuild.bat ${{ matrix.buildtype }} dll x86
      - name: Upload libnode.dll artifact
        uses: actions/upload-artifact@v4
        with:
          name: libnode-x86-${{ matrix.buildtype }}.dll
          path: out/${{ matrix.buildtype }}/libnode.dll
      - name: Upload libnode.lib artifact
        uses: actions/upload-artifact@v4
        with:
          name: libnode-x86-${{ matrix.buildtype }}.lib
          path: out/${{ matrix.buildtype }}/libnode.lib
      - name: Create a build archive
        uses: vimtor/action-zip@v1.2
        with:
          files: out/${{ matrix.buildtype }}/libnode.lib out/${{ matrix.buildtype }}/libnode.dll
          dest: libnode-win-x86-${{ matrix.buildtype }}.zip
      - name: Release the new binaries
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: "latest"
          files: libnode-win-x86-${{ matrix.buildtype }}.zip
